site:
  name: SanaDenta
  site: 'https://www.sanadenta.cz'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M
  seznamSiteVerificationId: 9k7x5u4TExzFXUB0ixFA8tBFzzwuzrhc

# Default SEO metadata
metadata:
  title:
    default: SanaDenta — Dentální hygiena Zlín-Malenovice
    template: '%s — SanaDenta'
  description: 'Šetrná dentální hygiena SanaDenta ve Zlíně-Malenovicích. Přijímáme nové pacienty od 1. října. Zajistěte si svůj termín online již dnes!'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: SanaDenta
    images:
      - url: '~/assets/images/og-image.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: cs
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

# NOTE: Theme switch related - Set to light:only to disable dark mode toggle
ui:
  theme: 'light:only'
